### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Recouse** [tam5/laravel-materialize#5]
module.js:457
    throw err;
    ^

Error: Cannot find module 'laravel-materialize'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\...\gulpfile.js:3:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by tam5** [comment]
Hi Firdavs,

Please share the steps you have taken so that I may reproduce this error. 

ex: Have you installed `laravel-materialize`?

**Comment by Recouse** [comment]
I installed package and made changes in gulpfile.js as you said there https://github.com/tam5/laravel-materialize#usage

**Comment by tam5** [comment]
You have run 'npm install laravel-materialize' as well as 'npm install' and then 'gulp'?

What OS are you working on? Node version?

**Comment by Recouse** [comment]
Yes.
Windows 10, node version 6.5.0

**Comment by tam5** [comment]
Unfortunately I have not been able to reproduce this error. I have successfully installed the package on Windows 10 with node v6.5.0 with a fresh install of Laravel.

If you have more information on how to reproduce this error I'd be happy to look into this further.

**Comment by Recouse** [comment]
Fixed it with `npm cache clean` and `npm install`.

**Comment by tam5** [comment]
:)
